from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Sequence

from .operating_time import SubdayClock
from .store_grid import GridPoint


@dataclass(frozen=True)
class ScheduledCustomerArrival:
    """One observed or manually supplied customer arrival.

    `at_absolute_minute` is relative to the supplied SubdayClock origin. It is
    not generated by a demand formula.
    """

    at_absolute_minute: int
    customer_id: str
    entry_point: GridPoint
    exit_point: GridPoint
    merchandise_fixture_ids: tuple[str, ...] = ()
    checkout_fixture_id: Optional[str] = None

    def __post_init__(self) -> None:
        if self.at_absolute_minute < 0:
            raise ValueError("at_absolute_minute must be >= 0")
        if not self.customer_id:
            raise ValueError("customer_id is required")


class ExplicitArrivalSchedule:
    """Replay queue for observed arrivals without inventing a spawn model."""

    def __init__(self, arrivals: Sequence[ScheduledCustomerArrival]) -> None:
        ordered = tuple(sorted(arrivals, key=lambda a: (a.at_absolute_minute, a.customer_id)))
        ids = [arrival.customer_id for arrival in ordered]
        if len(ids) != len(set(ids)):
            raise ValueError("customer_id must be unique within one arrival schedule")
        self._arrivals = ordered
        self._next_index = 0

    @property
    def arrivals(self) -> tuple[ScheduledCustomerArrival, ...]:
        return self._arrivals

    @property
    def pending_count(self) -> int:
        return len(self._arrivals) - self._next_index

    @property
    def complete(self) -> bool:
        return self._next_index >= len(self._arrivals)

    def pop_due(self, clock: SubdayClock) -> tuple[ScheduledCustomerArrival, ...]:
        due: list[ScheduledCustomerArrival] = []
        while self._next_index < len(self._arrivals):
            arrival = self._arrivals[self._next_index]
            if arrival.at_absolute_minute > clock.absolute_minutes:
                break
            due.append(arrival)
            self._next_index += 1
        return tuple(due)
